### ISSUE TITLE
Create additional endpoints for ridership

### ISSUE THREAD

**Issue by jaronheard** [hackoregon/transportation-systems-backend-2018#1]
Per our discussion tonight, we could use these additional information for the passenger census / ridership:

**Routes_annual_summary:**
Route
Route_grouping: eg. bus, train, other
Frequency_group: based on Jeff’s data, not yet available
sum_annual_ons - also breakdown by service_key
sum_annual_offs - also breakdown by service_key

To calculate the annual ons and offs:
For each year, sum ONS then multiply by 26 to get the total (there are two daily quarterly aggregates per year)
For service key W, multiply by 5 (5 weekdays per week)
For all other service keys, do not multiply

**Stop_ID_annual_summary:** 
Similar to the above, but at the the stop level
Routes - array
sum_annual_ons - also breakdown by service_key
sum_annual_offs - also breakdown by service_key
Lists all routes at stop
Also provide direction

**Comment by BrianHGrant** [comment]
I am playing with dome django based custom queries to see if this is possible to return dynamically. Will update

**Comment by znmeb** [comment]
Sounds good - I fixed the excess whitespace and reprojected the geometry to EPSG:4326 (longitude - latitude, GeoJSON default) but I haven't uploaded the new database yet. If either of you want it tonight / tomorrow, let me know and I'll push it to Google Drive. Otherwise I'm going to do some more geotagging and the time-of-day analysis on the congestion data before I push again.

**Comment by bhgrant8** [comment]
Ok so for `Routes_annual_summary`:

I created the following custom view:

```
class PassengerCensusRoutesAnnualViewSet(viewsets.ViewSetMixin, generics.ListAPIView):
    """
    This viewset will provide a list of Passenger Census by Routes in annual summary.
    """

    queryset = PassengerCensus.objects.all()
    serializer_class = PassengerCensusSerializer
    filter_backends = (PassengerCensusDateFilter,)
    pagination_class = LargeResultsSetPagination

    def list(self, request, *args, **kwargs):
        if request.GET.get('route', ' ') != ' ':
            this_route_number = request.GET.get('route', ' ')
            try:
                stops = PassengerCensus.objects.filter(route_number=this_route_number)
                if stops:
                    if request.GET.get('year', ' ') != ' ':
                        this_year = request.GET.get('year', ' ')
                        try:
                            stops = stops.filter(summary_begin_date__year=this_year)
                            if stops:
                                annual_sums = stops.aggregate(sum_ons=Sum('ons')*26, sum_offs=Sum('offs')*26)
                                weekday_sums = stops.filter(service_key__icontains="W").aggregate(sum_ons=Sum('ons')*5, sum_offs=Sum('offs')*5)
                                serialized_stops = PassengerCensusSerializer(stops, many=True)
                                return Response({'route_number': this_route_number,
                                    'year': this_year,
                                    'total_stops': stops.count(),
                                    'stops': serialized_stops.data,
                                    'annual_sums': annual_sums,
                                    'weekday_sums': weekday_sums
                                    })
                            else:
                                return Response('No Data found for Route Number and Year', status=status.HTTP_404_NOT_FOUND)
                        except ValueError:
                            return Response('Search year must be four digit year', status=status.HTTP_400_BAD_REQUEST)
                    else:
                        return Response('Must include a year for search', status=status.HTTP_400_BAD_REQUEST)
                else:
                    return Response('Route Number not found', status=status.HTTP_404_NOT_FOUND)
            except ValueError:
                return Response('Route Number must be integer', status=status.HTTP_400_BAD_REQUEST)
        else:
            return Response('Missing Route Number paramater', status=status.HTTP_400_BAD_REQUEST)
```

This takes the following query paremeters:

* route 
* year

Returning the following:

```
({'route_number': this_route_number,
                                    'year': this_year,
                                    'total_stops': stops.count(),
                                    'stops': serialized_stops.data,
                                    'annual_sums': annual_sums,
                                    'weekday_sums': weekday_sums
                                    })
```

Calculated fields:
* `total stops` - a count of the total number of stop events returned for the route in a given year
* `stops` - a GeoJSON FeatureCollection of indvidual census events which match the route number and year
* annual_sums - a json object which includes two aggregates: stops.aggregate(sum_ons=Sum('ons')*26, sum_offs=Sum('offs')*26)
* weekday_sums - filters for service_key then sums ons and offs and multiplies by 5

example response:

```
{
  "route_number": "1",
  "year": "2002",
  "total_stops": 604,
  "stops": {
    "type": "FeatureCollection",
    "features": [
       ...
      {
        "id": 5486,
        "type": "Feature",
        "geometry": {
          "type": "Point",
          "coordinates": [
            7643459.3657198,
            682097.38151998
          ]
        },
        "properties": {
          "summary_begin_date": "2002-03-03",
          "route_number": 1,
          "direction": 1,
          "service_key": "W  ",
          "stop_seq": 2650,
          "location_id": 7789,
          "public_location_description": "SW 6th & Salmon",
          "ons": 0,
          "offs": 7,
          "x_coord": 7643459.3657198,
          "y_coord": 682097.38151998
        }
      }
    ]
  },
  "annual_sums": {
    "sum_ons": 144118,
    "sum_offs": 145132
  },
  "weekday_sums": {
    "sum_ons": 17570,
    "sum_offs": 17460
  }
}
```

**Comment by jaronheard** [comment]
@BrianHGrant This is really great. My PR just modifies slightly the endpoints so that they are consistent in an annual summary format.

One thing that I didn't see - and maybe this exists - is that we should perform a check to see that we have two summaries per year. Right now the calculated statistics assume we have two, but I think would return an incorrect sum if we only have one.

**Comment by jaronheard** [comment]
Completed
